name: Python CI/CD Workflow
 
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.BINDU }}  # Ensure the token is used here as well
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Git to use the token
      run: |
        git config user.name "BinduSim"
        git config user.email "121910308005@gitam.in"
        git remote set-url origin https://x-access-token:${{ secrets.BINDU }}@github.com/BinduSim/accesstoken.git
    - name: Debug Git Configuration
      run: |
        git config --list
        git remote -v
    - name: Create and push to deployment branch
      run: |
        if git show-ref --verify --quiet refs/heads/deployment-branch; then
          git branch -D deployment-branch
        fi
        git checkout -b deployment-branch
        git push -f origin deployment-branch
      shell: bash

